# update configs on localhost
---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - ec2_metadata_facts:
    - name: render ctfd.service
      template:
        src: /tmp/ctfd.service.j2
        dest: /etc/systemd/system/ctfd.service
      vars:
        DB_PASS: "{{ lookup('aws_secret', '/ctfd/database/pass', region=ansible_ec2_placement_region) }}"
        DB_URL: "{{ lookup('aws_secret', '/ctfd/database/url', region=ansible_ec2_placement_region) }}"
        REDIS_URL: "{{ lookup('aws_secret', '/ctfd/redis/url', region=ansible_ec2_placement_region) }}"
        AWS_S3_BUCKET: "{{ lookup('aws_secret', '/ctfd/s3/bucket_name', region=ansible_ec2_placement_region) }}"
    - name: render .ctfd_secret_key
      copy:
        content: "{{ lookup('aws_secret', '/ctfd/app_key', region=ansible_ec2_placement_region) }}"
        dest: /opt/CTFd-2.5.0/.ctfd_secret_key

    - name: restart ctfd.service
      systemd:
        state: restarted
        daemon_reload: yes
        name: ctfd.service
