# update configs on localhost
---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: render ctfd.service
      template:
        src: /tmp/ctfd.service.j2
        dest: /etc/systemd/system/ctfd.service
      vars:
        DB_PASS: "{{ lookup('aws_secret', '/ctfd/database/password') }}"
        DB_URL: "{{ lookup('aws_secret', '/ctfd/database/url') }}"
        REDIS_URL: "{{ lookup('aws_secret', '/ctfd/redis/url') }}"
        AWS_S3_BUCKET: "{{ lookup('aws_secret', '/ctfd/s3/bucket_name') }}"
    - name: render .ctfd_secret_key
      copy:
        content: "{{ lookup('aws_secret', '/ctfd/app_key') }}"

    - name: restart ctfd.service
      systemd:
        state: restarted
        daemon_reload: yes
        name: ctfd.service
